### ISSUE TITLE
Feature request.

### ISSUE THREAD

**Issue by Moosites** [joomla-projects/gsoc22_accessibility-plugin-script#19]
Add the option for users who have no need for accessibility options to hide the feature completely whilst logged in.

**Comment by chmst** [comment]
Thank you,this is a valid feature request. Unfortunately this repo is abandonned as the accessibility plugin now is integrated into Joomla Core. 
Could you please repeat your request here? https://github.com/joomla/joomla-cms/issues

**Comment by drmenzelit** [comment]
You can change the access level for the plugin to "Guest", so it will be only visible for not logged in visitors. If you need more differentiation when you have users that could login into the site and need the accessibility options, then you can create different user groups and access levels.

Closing because it is the wrong repository to ask for this feature.
